### ISSUE TITLE
使用Qwen-1.5B采样short answer的细节

### ISSUE THREAD

**Issue by CurryxIaoHu** [VainF/Thinkless#3]
论文里提到“The corresponding short-form answers are derived using Qwen2.5-Math-1.5B-Instruct [41], a compact instruction-tuned model optimized for concise mathematical responses.” 请问作者这里采样short answer的细节是什么？例如采样次数、验证答案正确性的方法（math_verify?)、采样Promot、温度等；非常感谢！

**Comment by VainF** [comment]
Hi @CurryxIaoHu, we used the following configs for generation:

```
dataset_name: default
dataset_path: open-thoughts/OpenThoughts2-1M
doc_to_target: answer
doc_to_text: problem
process_docs: !function utils.process_docs_1m_filtered
filter_list:
- filter:
  - function: regex
    regex_pattern: ''
  - function: take_first
  name: strict-match
generation_kwargs:
  until:
  - <｜end▁of▁sentence｜>
  - <|im_end|>
  do_sample: true
  temperature: 0.6
  max_gen_toks: 8192
tag:
- chain_of_thought
metadata:
  version: 3.0
metric_list:
- aggregation: mean
  higher_is_better: true
  ignore_case: true
  ignore_punctuation: false
  metric: exact_match
  regexes_to_ignore:
  - ','
num_fewshot: 0
output_type: generate_until
repeats: 1
task: gen_open_thoughts_1m
test_split: train
```
